### ISSUE TITLE
Screenshot when scraping

### ISSUE THREAD

**Issue by cguess** [cguess/birdsong#9]
We need to take screenshots in addition to the API. This means adding capybara etc to the gem which is a bit of a pain, but necessary.

**Comment by cguess** [comment]
Things to do:
- [ ] Add capybara/selinium to the Gemfile
- [ ] Ensure the server settings align with others (for Firefox, since we want a "full page" screenshot)
- [ ] Write tests to verify it's running
- [ ] Add file path to the response

**Comment by oneroyalace** [comment]
Ah wait! We can do this from Hypatia. https://github.com/TechAndCheck/hypatia/blob/77987bda49c5f42db086c2ada9cb107434fd08a5/app/media_sources/media_source.rb#L51-L62

**Comment by cguess** [comment]
as @oneroyalace said, this is better done in Hypatia, closing
